import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import AuthSession from "./context/AuthSession";
import ToasterContext from "./context/ToasterContext";
import Footer from "@/components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.JPG" />
        <title>Food App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <AuthSession>
          <ToasterContext />
          <Header />
          {children}
          <Footer />
        </AuthSession>
      </body>
    </html>
  );
}
